"""Add resilience fields v2

Revision ID: 0bee69d3bd29
Revises: 61034897bc59
Create Date: 2026-04-02 02:35:42.098925
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0bee69d3bd29'
down_revision: Union[str, None] = '61034897bc59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('checkpoint_data', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'checkpoint_data')
    # ### end Alembic commands ###
