"""add_causal_and_inhibition_fields_to_subtasks

Revision ID: 33bbc921964e
Revises: 0bee69d3bd29
Create Date: 2026-04-05 01:31:16.492596
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '33bbc921964e'
down_revision: str | None = '0bee69d3bd29'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('causal_anchor', sa.Text(), nullable=True))
    op.add_column('subtasks', sa.Column('inhibition_signals', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtasks', 'inhibition_signals')
    op.drop_column('subtasks', 'causal_anchor')
    # ### end Alembic commands ###
