"""add_meta_governor_tables

Revision ID: 54a09b9b7ba4
Revises: c2e573c6206b
Create Date: 2026-04-27 00:48:54.364488
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '54a09b9b7ba4'
down_revision: Union[str, None] = 'c2e573c6206b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governor_conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('domain_a', sa.Enum('WORKFLOW', 'INCIDENT', 'APPROVAL', 'POLICY', 'REPAIR', 'META', name='governordomain'), nullable=False),
    sa.Column('domain_b', sa.Enum('WORKFLOW', 'INCIDENT', 'APPROVAL', 'POLICY', 'REPAIR', 'META', name='governordomain'), nullable=False),
    sa.Column('decision_a', sa.String(length=64), nullable=False),
    sa.Column('decision_b', sa.String(length=64), nullable=False),
    sa.Column('conflict_type', sa.Enum('NONE', 'RISK_DISAGREEMENT', 'ACTION_DISAGREEMENT', 'POLICY_BLOCK', 'QUORUM_REQUIRED', 'PRIME_REQUIRED', name='governorconflicttype'), nullable=False),
    sa.Column('conflict_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governor_conflicts_case_id'), 'governor_conflicts', ['case_id'], unique=False)
    op.create_index(op.f('ix_governor_conflicts_conflict_type'), 'governor_conflicts', ['conflict_type'], unique=False)
    op.create_index(op.f('ix_governor_conflicts_created_at'), 'governor_conflicts', ['created_at'], unique=False)
    op.create_index(op.f('ix_governor_conflicts_project_id'), 'governor_conflicts', ['project_id'], unique=False)
    op.create_index(op.f('ix_governor_conflicts_status'), 'governor_conflicts', ['status'], unique=False)
    op.create_table('meta_governor_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('winning_domain', sa.Enum('WORKFLOW', 'INCIDENT', 'APPROVAL', 'POLICY', 'REPAIR', 'META', name='governordomain'), nullable=True),
    sa.Column('final_decision', sa.String(length=64), nullable=False),
    sa.Column('final_risk_class', sa.String(length=16), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('applied_constraints', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_governor_decisions_case_id'), 'meta_governor_decisions', ['case_id'], unique=False)
    op.create_index(op.f('ix_meta_governor_decisions_created_at'), 'meta_governor_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_meta_governor_decisions_project_id'), 'meta_governor_decisions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_governor_decisions_project_id'), table_name='meta_governor_decisions')
    op.drop_index(op.f('ix_meta_governor_decisions_created_at'), table_name='meta_governor_decisions')
    op.drop_index(op.f('ix_meta_governor_decisions_case_id'), table_name='meta_governor_decisions')
    op.drop_table('meta_governor_decisions')
    op.drop_index(op.f('ix_governor_conflicts_status'), table_name='governor_conflicts')
    op.drop_index(op.f('ix_governor_conflicts_project_id'), table_name='governor_conflicts')
    op.drop_index(op.f('ix_governor_conflicts_created_at'), table_name='governor_conflicts')
    op.drop_index(op.f('ix_governor_conflicts_conflict_type'), table_name='governor_conflicts')
    op.drop_index(op.f('ix_governor_conflicts_case_id'), table_name='governor_conflicts')
    op.drop_table('governor_conflicts')
    # ### end Alembic commands ###
