"""Add internal_monologue to subtasks

Revision ID: 61034897bc59
Revises: af7ebd1309a2
Create Date: 2026-04-01 23:33:25.445042
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '61034897bc59'
down_revision: Union[str, None] = 'af7ebd1309a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_patch_logs_class_outcome'), table_name='repair_patch_logs')
    op.drop_index(op.f('ix_repair_patch_logs_job_id'), table_name='repair_patch_logs')
    op.drop_index(op.f('ix_repair_patch_logs_record_id'), table_name='repair_patch_logs')
    op.drop_table('repair_patch_logs')
    op.drop_index(op.f('ix_repair_proposals_decision'), table_name='repair_proposals')
    op.drop_index(op.f('ix_repair_proposals_job_id'), table_name='repair_proposals')
    op.drop_index(op.f('ix_repair_proposals_pr_id'), table_name='repair_proposals')
    op.drop_table('repair_proposals')
    op.drop_index(op.f('ix_repair_incidents_incident_id'), table_name='repair_incidents')
    op.drop_index(op.f('ix_repair_incidents_module_status'), table_name='repair_incidents')
    op.drop_index(op.f('ix_repair_incidents_severity_status'), table_name='repair_incidents')
    op.drop_table('repair_incidents')
    op.drop_index(op.f('ix_repair_vector_lessons_lesson_id'), table_name='repair_vector_lessons')
    op.drop_index(op.f('ix_repair_vector_lessons_module'), table_name='repair_vector_lessons')
    op.drop_index(op.f('ix_repair_vector_lessons_module_created'), table_name='repair_vector_lessons')
    op.drop_table('repair_vector_lessons')
    op.drop_index(op.f('ix_repair_jobs_incident_id'), table_name='repair_jobs')
    op.drop_index(op.f('ix_repair_jobs_job_id'), table_name='repair_jobs')
    op.drop_index(op.f('ix_repair_jobs_status_created'), table_name='repair_jobs')
    op.drop_table('repair_jobs')
    op.add_column('agent_health_logs', sa.Column('score', sa.Float(), nullable=False))
    op.add_column('agent_health_logs', sa.Column('state', sa.String(length=32), nullable=True))
    op.add_column('agent_health_logs', sa.Column('severity', sa.String(length=32), nullable=True))
    op.add_column('agent_health_logs', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('agent_health_logs', sa.Column('action', sa.String(length=64), nullable=True))
    op.drop_column('agent_health_logs', 'detail')
    op.drop_column('agent_health_logs', 'event')
    op.drop_column('agent_health_logs', 'health_score')
    op.alter_column('api_metrics', 'endpoint',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('api_metrics', 'method',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=8),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('api_metrics', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('api_metrics', 'response_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('api_metrics', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('api_metrics', 'trace_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('api_metrics', 'error_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.create_index('ix_api_metrics_created', 'api_metrics', ['created_at'], unique=False)
    op.create_index('ix_api_metrics_endpoint_created', 'api_metrics', ['endpoint', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_metrics_trace_id'), 'api_metrics', ['trace_id'], unique=False)
    op.drop_column('api_metrics', 'sampled')
    op.alter_column('ceo_decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('ceo_decisions_opportunity_id_fkey'), 'ceo_decisions', type_='foreignkey')
    op.create_foreign_key(None, 'ceo_decisions', 'improvement_opportunities', ['opportunity_id'], ['id'])
    op.alter_column('ceo_performance_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('ceo_performance_logs_suggestion_id_fkey'), 'ceo_performance_logs', type_='foreignkey')
    op.drop_constraint(op.f('ceo_performance_logs_project_id_fkey'), 'ceo_performance_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ceo_performance_logs', 'ceo_suggested_tasks', ['suggestion_id'], ['id'])
    op.create_foreign_key(None, 'ceo_performance_logs', 'projects', ['project_id'], ['id'])
    op.alter_column('ceo_suggested_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('ceo_suggested_tasks_opportunity_id_fkey'), 'ceo_suggested_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'ceo_suggested_tasks', 'improvement_opportunities', ['opportunity_id'], ['id'])
    op.alter_column('domain_event_logs', 'phase',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_index(op.f('ix_domain_event_logs_severity'), table_name='domain_event_logs')
    op.alter_column('improvement_opportunities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_improvement_opportunities_hash'), table_name='improvement_opportunities')
    op.drop_index(op.f('ix_improvement_opportunities_priority'), table_name='improvement_opportunities')
    op.create_index(op.f('ix_improvement_opportunities_priority_score'), 'improvement_opportunities', ['priority_score'], unique=False)
    op.create_unique_constraint(None, 'improvement_opportunities', ['pattern_hash'])
    op.alter_column('llm_cost_logs', 'model',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('llm_cost_logs', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_column('llm_cost_logs', 'error')
    op.drop_column('llm_cost_logs', 'subtask_id')
    op.alter_column('memories', 'category',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('memories', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.create_index(op.f('ix_memories_category'), 'memories', ['category'], unique=False)
    op.drop_index(op.f('ix_model_router_logs_role'), table_name='model_router_logs')
    op.create_index(op.f('ix_model_router_logs_agent_role'), 'model_router_logs', ['agent_role'], unique=False)
    op.create_index(op.f('ix_model_router_logs_complexity'), 'model_router_logs', ['complexity'], unique=False)
    op.create_index(op.f('ix_model_router_logs_created_at'), 'model_router_logs', ['created_at'], unique=False)
    op.alter_column('projects', 'budget_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.add_column('rate_limit_counters', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('rate_limit_counters', 'key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_index(op.f('ix_rate_limit_counters_window_end'), table_name='rate_limit_counters')
    op.drop_index(op.f('ix_rate_limit_counters_key'), table_name='rate_limit_counters')
    op.create_index(op.f('ix_rate_limit_counters_key'), 'rate_limit_counters', ['key'], unique=True)
    op.drop_column('rate_limit_counters', 'window_start')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_unique_constraint(None, 'refresh_tokens', ['token'])
    op.add_column('subtasks', sa.Column('internal_monologue', sa.Text(), nullable=True))
    op.alter_column('subtasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_subtasks_project_id'), table_name='subtasks')
    op.alter_column('task_logs', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('task_logs', 'level',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('task_logs', 'event',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.create_index(op.f('ix_task_logs_event'), 'task_logs', ['event'], unique=False)
    op.create_index('ix_task_logs_project_created', 'task_logs', ['project_id', 'created_at'], unique=False)
    op.add_column('telegram_command_logs', sa.Column('arguments', sa.Text(), nullable=True))
    op.add_column('telegram_command_logs', sa.Column('project_id', sa.UUID(), nullable=True))
    op.alter_column('telegram_command_logs', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('telegram_command_logs', 'command',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index(op.f('ix_telegram_command_logs_created_at'), 'telegram_command_logs', ['created_at'], unique=False)
    op.drop_column('telegram_command_logs', 'args')
    op.add_column('telegram_users', sa.Column('full_name', sa.String(length=256), nullable=True))
    op.add_column('telegram_users', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('telegram_users', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('telegram_users', sa.Column('command_count', sa.Integer(), nullable=True))
    op.alter_column('telegram_users', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('telegram_users', 'is_authorized',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'telegram_users', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('telegram_users', 'last_seen')
    op.alter_column('webhook_subscriptions', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.alter_column('webhook_subscriptions', 'secret',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('webhook_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('webhook_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('webhook_subscriptions', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_subscriptions', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.alter_column('webhook_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('webhook_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('webhook_subscriptions', 'secret',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=256),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('webhook_subscriptions', 'url',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('telegram_users', sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'telegram_users', type_='foreignkey')
    op.alter_column('telegram_users', 'is_authorized',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('telegram_users', 'telegram_id',
               existing_type=sa.String(length=32),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('telegram_users', 'command_count')
    op.drop_column('telegram_users', 'last_seen_at')
    op.drop_column('telegram_users', 'user_id')
    op.drop_column('telegram_users', 'full_name')
    op.add_column('telegram_command_logs', sa.Column('args', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_telegram_command_logs_created_at'), table_name='telegram_command_logs')
    op.alter_column('telegram_command_logs', 'command',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('telegram_command_logs', 'telegram_id',
               existing_type=sa.String(length=32),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('telegram_command_logs', 'project_id')
    op.drop_column('telegram_command_logs', 'arguments')
    op.drop_index('ix_task_logs_project_created', table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_event'), table_name='task_logs')
    op.alter_column('task_logs', 'event',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('task_logs', 'level',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('task_logs', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_subtasks_project_id'), 'subtasks', ['project_id'], unique=False)
    op.alter_column('subtasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('subtasks', 'internal_monologue')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.add_column('rate_limit_counters', sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_rate_limit_counters_key'), table_name='rate_limit_counters')
    op.create_index(op.f('ix_rate_limit_counters_key'), 'rate_limit_counters', ['key'], unique=False)
    op.create_index(op.f('ix_rate_limit_counters_window_end'), 'rate_limit_counters', ['window_end'], unique=False)
    op.alter_column('rate_limit_counters', 'key',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('rate_limit_counters', 'updated_at')
    op.alter_column('projects', 'budget_limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_index(op.f('ix_model_router_logs_created_at'), table_name='model_router_logs')
    op.drop_index(op.f('ix_model_router_logs_complexity'), table_name='model_router_logs')
    op.drop_index(op.f('ix_model_router_logs_agent_role'), table_name='model_router_logs')
    op.create_index(op.f('ix_model_router_logs_role'), 'model_router_logs', ['agent_role'], unique=False)
    op.drop_index(op.f('ix_memories_category'), table_name='memories')
    op.alter_column('memories', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('memories', 'category',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.add_column('llm_cost_logs', sa.Column('subtask_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('llm_cost_logs', sa.Column('error', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.alter_column('llm_cost_logs', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('llm_cost_logs', 'model',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint(None, 'improvement_opportunities', type_='unique')
    op.drop_index(op.f('ix_improvement_opportunities_priority_score'), table_name='improvement_opportunities')
    op.create_index(op.f('ix_improvement_opportunities_priority'), 'improvement_opportunities', ['priority_score'], unique=False)
    op.create_index(op.f('ix_improvement_opportunities_hash'), 'improvement_opportunities', ['pattern_hash'], unique=True)
    op.alter_column('improvement_opportunities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_domain_event_logs_severity'), 'domain_event_logs', ['severity'], unique=False)
    op.alter_column('domain_event_logs', 'phase',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint(None, 'ceo_suggested_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('ceo_suggested_tasks_opportunity_id_fkey'), 'ceo_suggested_tasks', 'improvement_opportunities', ['opportunity_id'], ['id'], ondelete='SET NULL')
    op.alter_column('ceo_suggested_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'ceo_performance_logs', type_='foreignkey')
    op.drop_constraint(None, 'ceo_performance_logs', type_='foreignkey')
    op.create_foreign_key(op.f('ceo_performance_logs_project_id_fkey'), 'ceo_performance_logs', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('ceo_performance_logs_suggestion_id_fkey'), 'ceo_performance_logs', 'ceo_suggested_tasks', ['suggestion_id'], ['id'], ondelete='SET NULL')
    op.alter_column('ceo_performance_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'ceo_decisions', type_='foreignkey')
    op.create_foreign_key(op.f('ceo_decisions_opportunity_id_fkey'), 'ceo_decisions', 'improvement_opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ceo_decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('api_metrics', sa.Column('sampled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_api_metrics_trace_id'), table_name='api_metrics')
    op.drop_index('ix_api_metrics_endpoint_created', table_name='api_metrics')
    op.drop_index('ix_api_metrics_created', table_name='api_metrics')
    op.alter_column('api_metrics', 'error_type',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('api_metrics', 'trace_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('api_metrics', 'ip_address',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('api_metrics', 'response_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('api_metrics', 'status_code',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('api_metrics', 'method',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('api_metrics', 'endpoint',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('agent_health_logs', sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=True))
    op.add_column('agent_health_logs', sa.Column('event', sa.VARCHAR(length=64), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
    op.add_column('agent_health_logs', sa.Column('detail', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.drop_column('agent_health_logs', 'action')
    op.drop_column('agent_health_logs', 'message')
    op.drop_column('agent_health_logs', 'severity')
    op.drop_column('agent_health_logs', 'state')
    op.drop_column('agent_health_logs', 'score')
    op.create_table('repair_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('validation_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('pr_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('branch_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('diff', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('error_detail', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('history', sa.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('meta', sa.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('repair_jobs_pkey')),
    sa.UniqueConstraint('job_id', name=op.f('repair_jobs_job_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_repair_jobs_status_created'), 'repair_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_repair_jobs_job_id'), 'repair_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_repair_jobs_incident_id'), 'repair_jobs', ['incident_id'], unique=False)
    op.create_table('repair_vector_lessons',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('symptom', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags', sa.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('repair_vector_lessons_pkey'))
    )
    op.create_index(op.f('ix_repair_vector_lessons_module_created'), 'repair_vector_lessons', ['module', 'created_at'], unique=False)
    op.create_index(op.f('ix_repair_vector_lessons_module'), 'repair_vector_lessons', ['module'], unique=False)
    op.create_index(op.f('ix_repair_vector_lessons_lesson_id'), 'repair_vector_lessons', ['lesson_id'], unique=True)
    op.create_table('repair_incidents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('symptom', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stack_trace', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('suspected_files', sa.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'"), autoincrement=False, nullable=True),
    sa.Column('failing_tests', sa.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'"), autoincrement=False, nullable=True),
    sa.Column('reproduction_hint', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('context_data', sa.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'"), autoincrement=False, nullable=True),
    sa.Column('occurrence_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('repair_incidents_pkey')),
    sa.UniqueConstraint('incident_id', name=op.f('repair_incidents_incident_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_repair_incidents_severity_status'), 'repair_incidents', ['severity', 'status'], unique=False)
    op.create_index(op.f('ix_repair_incidents_module_status'), 'repair_incidents', ['module', 'status'], unique=False)
    op.create_index(op.f('ix_repair_incidents_incident_id'), 'repair_incidents', ['incident_id'], unique=False)
    op.create_table('repair_proposals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pr_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('branch_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('diff', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('changed_files', sa.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'"), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=16), server_default=sa.text("'low'::character varying"), autoincrement=False, nullable=True),
    sa.Column('validation_summary', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('auto_merge', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('decided_by', sa.VARCHAR(length=128), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('repair_proposals_pkey')),
    sa.UniqueConstraint('pr_id', name=op.f('repair_proposals_pr_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_repair_proposals_pr_id'), 'repair_proposals', ['pr_id'], unique=False)
    op.create_index(op.f('ix_repair_proposals_job_id'), 'repair_proposals', ['job_id'], unique=False)
    op.create_index(op.f('ix_repair_proposals_decision'), 'repair_proposals', ['decision'], unique=False)
    op.create_table('repair_patch_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('incident_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('classification', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('target_files', sa.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'"), autoincrement=False, nullable=True),
    sa.Column('diff_size_lines', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('validation_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('repair_patch_logs_pkey')),
    sa.UniqueConstraint('record_id', name=op.f('repair_patch_logs_record_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_repair_patch_logs_record_id'), 'repair_patch_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_repair_patch_logs_job_id'), 'repair_patch_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_repair_patch_logs_class_outcome'), 'repair_patch_logs', ['classification', 'outcome'], unique=False)
    # ### end Alembic commands ###
