"""add_phase_80_sovereign_goals_and_goal_id

Revision ID: 7cc9f44bc8d0
Revises: 33bbc921964e
Create Date: 2026-04-04 22:32:03.846350
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7cc9f44bc8d0'
down_revision: str | None = '33bbc921964e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sovereign_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('vision_statement', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('kpis', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ceo_suggested_tasks', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('ceo_suggested_tasks', sa.Column('plan_hierarchy', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('ceo_suggested_tasks', sa.Column('goal_id', sa.UUID(), nullable=True))
    op.add_column('ceo_suggested_tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('ceo_suggested_tasks', 'priority',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.create_foreign_key(None, 'ceo_suggested_tasks', 'projects', ['created_task_id'], ['id'])
    op.create_foreign_key(None, 'ceo_suggested_tasks', 'ceo_suggested_tasks', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'ceo_suggested_tasks', 'sovereign_goals', ['goal_id'], ['id'])
    # ── llm_cost_logs hardening ──────────────────────────
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    llm_cols = [c['name'] for c in inspector.get_columns('llm_cost_logs')]

    if 'agent_role' not in llm_cols:
        op.add_column('llm_cost_logs', sa.Column('agent_role', sa.String(length=50), nullable=True))

    op.execute('DROP INDEX IF EXISTS idx_llm_cost_logs_role')

    # Check if index already exists to prevent duplication error
    llm_indexes = [idx['name'] for idx in inspector.get_indexes('llm_cost_logs')]
    if 'ix_llm_cost_logs_agent_role' not in llm_indexes:
        op.create_index(op.f('ix_llm_cost_logs_agent_role'), 'llm_cost_logs', ['agent_role'], unique=False)

    # ── memories hardening ───────────────────────────────
    mem_cols = [c['name'] for c in inspector.get_columns('memories')]
    if 'parent_id' not in mem_cols:
        op.add_column('memories', sa.Column('parent_id', sa.UUID(), nullable=True))
    if 'cause_id' not in mem_cols:
        op.add_column('memories', sa.Column('cause_id', sa.UUID(), nullable=True))

    mem_indexes = [idx['name'] for idx in inspector.get_indexes('memories')]
    if 'ix_memories_cause_id' not in mem_indexes:
        op.create_index(op.f('ix_memories_cause_id'), 'memories', ['cause_id'], unique=False)
    if 'ix_memories_parent_id' not in mem_indexes:
        op.create_index(op.f('ix_memories_parent_id'), 'memories', ['parent_id'], unique=False)

    # Check FK before adding
    mem_fks = inspector.get_foreign_keys('memories')
    if not any('parent_id' in fk['constrained_columns'] for fk in mem_fks):
        op.create_foreign_key(None, 'memories', 'memories', ['parent_id'], ['id'])

    # ── projects hardening ───────────────────────────────
    proj_cols = [c['name'] for c in inspector.get_columns('projects')]
    if 'goal_id' not in proj_cols:
        op.add_column('projects', sa.Column('goal_id', sa.UUID(), nullable=True))

    proj_fks = inspector.get_foreign_keys('projects')
    if not any('goal_id' in fk['constrained_columns'] for fk in proj_fks):
        op.create_foreign_key(None, 'projects', 'sovereign_goals', ['goal_id'], ['id'], ondelete='SET NULL')

    # ── subtasks hardening ───────────────────────────────
    # Type variant fix for subtasks
    op.alter_column('subtasks', 'inhibition_signals',
               existing_type=postgresql.JSON(),
               type_=sa.JSON().with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=True)

    subtask_cols = [c['name'] for c in inspector.get_columns('subtasks')]
    if 'parent_id' not in subtask_cols:
        op.add_column('subtasks', sa.Column('parent_id', sa.UUID(), nullable=True))

    op.execute('ALTER TABLE subtasks DROP CONSTRAINT IF EXISTS subtasks_parent_id_fkey')

    # Check FK before adding
    subtask_fks = inspector.get_foreign_keys('subtasks')
    if not any('parent_id' in fk['constrained_columns'] for fk in subtask_fks):
        op.create_foreign_key(None, 'subtasks', 'subtasks', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.create_foreign_key(op.f('subtasks_parent_id_fkey'), 'subtasks', 'subtasks', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('subtasks', 'inhibition_signals',
               existing_type=sa.JSON().with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(),
               existing_nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'goal_id')
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_index(op.f('ix_memories_parent_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_cause_id'), table_name='memories')
    op.drop_column('memories', 'cause_id')
    op.drop_column('memories', 'parent_id')
    op.drop_index(op.f('ix_llm_cost_logs_agent_role'), table_name='llm_cost_logs')
    op.create_index(op.f('idx_llm_cost_logs_role'), 'llm_cost_logs', ['agent_role'], unique=False)
    op.drop_constraint(None, 'ceo_suggested_tasks', type_='foreignkey')
    op.drop_constraint(None, 'ceo_suggested_tasks', type_='foreignkey')
    op.drop_constraint(None, 'ceo_suggested_tasks', type_='foreignkey')
    op.alter_column('ceo_suggested_tasks', 'priority',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_column('ceo_suggested_tasks', 'updated_at')
    op.drop_column('ceo_suggested_tasks', 'goal_id')
    op.drop_column('ceo_suggested_tasks', 'plan_hierarchy')
    op.drop_column('ceo_suggested_tasks', 'parent_id')
    op.drop_table('sovereign_goals')
    # ### end Alembic commands ###
