"""add_governor_calibrations

Revision ID: c2e573c6206b
Revises: fd994d364247
Create Date: 2026-04-27 00:39:06.957956
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c2e573c6206b'
down_revision: Union[str, None] = 'fd994d364247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import libs.db.base
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governor_calibrations',
    sa.Column('id', libs.db.base.GUID(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Float(), nullable=False),
    sa.Column('proposed_value', sa.Float(), nullable=False),
    sa.Column('applied_value', sa.Float(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'APPLIED', 'REJECTED', 'ROLLED_BACK', name='calibrationstatus'), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('rolled_back_from', libs.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governor_calibrations_created_at'), 'governor_calibrations', ['created_at'], unique=False)
    op.create_index(op.f('ix_governor_calibrations_parameter_name'), 'governor_calibrations', ['parameter_name'], unique=False)
    op.create_index(op.f('ix_governor_calibrations_status'), 'governor_calibrations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_governor_calibrations_status'), table_name='governor_calibrations')
    op.drop_index(op.f('ix_governor_calibrations_parameter_name'), table_name='governor_calibrations')
    op.drop_index(op.f('ix_governor_calibrations_created_at'), table_name='governor_calibrations')
    op.drop_table('governor_calibrations')
    # ### end Alembic commands ###

