"""add_governor_resilience_tables

Revision ID: dfd787c12448
Revises: 54a09b9b7ba4
Create Date: 2026-04-27 01:05:40.364488
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM

revision: str = 'dfd787c12448'
down_revision: Union[str, None] = '54a09b9b7ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governor_circuit_breakers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', PG_ENUM('WORKFLOW', 'INCIDENT', 'APPROVAL', 'POLICY', 'REPAIR', 'META', name='governordomain', create_type=False), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_threshold', sa.Integer(), nullable=True),
    sa.Column('recovery_mode', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Since governordomain already exists, we might need to tell Alembic to skip creating it or handle it.
    # Actually, in PostgreSQL, if an ENUM exists, CREATE TYPE will fail.
    # However, op.create_table will try to create the enum type if it's new.
    # I'll use a safer approach: check if types exist or just use existing ones.
    
    op.create_index(op.f('ix_governor_circuit_breakers_domain'), 'governor_circuit_breakers', ['domain'], unique=False)
    op.create_index(op.f('ix_governor_circuit_breakers_state'), 'governor_circuit_breakers', ['state'], unique=False)
    
    op.create_table('governor_drills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drill_type', sa.Enum('DOMAIN_TIMEOUT', 'META_TIMEOUT', 'CONFLICT_STORM', 'FALSE_ESCALATION_BURST', 'REPLAY_STORM', 'POLICY_VETO_FLOOD', 'LINEAGE_FAILURE', 'DB_DEGRADED', name='governordrilltype'), nullable=False),
    sa.Column('target_domain', PG_ENUM('WORKFLOW', 'INCIDENT', 'APPROVAL', 'POLICY', 'REPAIR', 'META', name='governordomain', create_type=False), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'RUNNING', 'PASSED', 'FAILED', 'ABORTED', name='governordrillstatus'), nullable=False),
    sa.Column('scenario_payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governor_drills_created_at'), 'governor_drills', ['created_at'], unique=False)
    op.create_index(op.f('ix_governor_drills_drill_type'), 'governor_drills', ['drill_type'], unique=False)
    op.create_index(op.f('ix_governor_drills_status'), 'governor_drills', ['status'], unique=False)

    op.create_table('governor_runtime',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', PG_ENUM('WORKFLOW', 'INCIDENT', 'APPROVAL', 'POLICY', 'REPAIR', 'META', name='governordomain', create_type=False), nullable=False),
    sa.Column('runtime_status', sa.Enum('HEALTHY', 'DEGRADED', 'FROZEN', 'ISOLATED', 'FAILED', name='governorruntimestatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('freeze_mode', sa.Integer(), nullable=True),
    sa.Column('advisory_only', sa.Integer(), nullable=True),
    sa.Column('last_healthy_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governor_runtime_domain'), 'governor_runtime', ['domain'], unique=False)
    op.create_index(op.f('ix_governor_runtime_runtime_status'), 'governor_runtime', ['runtime_status'], unique=False)

    op.create_table('governor_slo_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', PG_ENUM('WORKFLOW', 'INCIDENT', 'APPROVAL', 'POLICY', 'REPAIR', 'META', name='governordomain', create_type=False), nullable=False),
    sa.Column('operation_name', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('sample_window', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governor_slo_samples_created_at'), 'governor_slo_samples', ['created_at'], unique=False)
    op.create_index(op.f('ix_governor_slo_samples_domain'), 'governor_slo_samples', ['domain'], unique=False)
    op.create_index(op.f('ix_governor_slo_samples_operation_name'), 'governor_slo_samples', ['operation_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_governor_slo_samples_operation_name'), table_name='governor_slo_samples')
    op.drop_index(op.f('ix_governor_slo_samples_domain'), table_name='governor_slo_samples')
    op.drop_index(op.f('ix_governor_slo_samples_created_at'), table_name='governor_slo_samples')
    op.drop_table('governor_slo_samples')
    op.drop_index(op.f('ix_governor_runtime_runtime_status'), table_name='governor_runtime')
    op.drop_index(op.f('ix_governor_runtime_domain'), table_name='governor_runtime')
    op.drop_table('governor_runtime')
    op.drop_index(op.f('ix_governor_drills_status'), table_name='governor_drills')
    op.drop_index(op.f('ix_governor_drills_drill_type'), table_name='governor_drills')
    op.drop_index(op.f('ix_governor_drills_created_at'), table_name='governor_drills')
    op.drop_table('governor_drills')
    op.drop_index(op.f('ix_governor_circuit_breakers_state'), table_name='governor_circuit_breakers')
    op.drop_index(op.f('ix_governor_circuit_breakers_domain'), table_name='governor_circuit_breakers')
    op.drop_table('governor_circuit_breakers')
    # ### end Alembic commands ###
