/* THIS FILE WAS GENERATED BY PAYLOAD DO NOT EDIT */
import { RootLayout } from '@payloadcms/next/layouts'
import config from '../../../payload.config'
import { importMap } from './admin/importMap'
import './custom.css'

type Args = {
  children: React.ReactNode
}

const Layout = ({ children }: Args) => RootLayout({ children, config, importMap })

export default Layout
