"use client";

import React from "react";
import { useList, useUpdate, useNavigation } from "@refinedev/core";
import { 
    Cpu, 
    ShieldCheck, 
    AlertTriangle, 
    Code2, 
    Check, 
    X,
    ExternalLink,
    Terminal,
    Clock
} from "lucide-react";

export default function ImprovementsPage() {
    const { query: { data, isLoading, refetch } } = useList({
        resource: "improvements",
        pagination: { pageSize: 20 },
        sorters: [{ field: "created_at", order: "desc" }]
    });

    const { mutate: updateStatus } = useUpdate();

    const handleApprove = (id: string) => {
        updateStatus({
            resource: "improvements",
            id,
            values: { status: "approved" },
            successNotification: { message: "Patch approved for deployment", type: "success" }
        }, {
            onSuccess: () => refetch()
        });
    };

    const handleReject = (id: string) => {
        updateStatus({
            resource: "improvements",
            id,
            values: { status: "rejected" },
            successNotification: { message: "Patch rejected", type: "error" }
        }, {
            onSuccess: () => refetch()
        });
    };

    const getStatusStyle = (status: string) => {
        switch (status.toLowerCase()) {
            case "applied": return "text-green-400 bg-green-400/10 border-green-400/20";
            case "pending": return "text-yellow-400 bg-yellow-400/10 border-yellow-400/20";
            case "rejected": return "text-red-400 bg-red-400/10 border-red-400/20";
            default: return "text-blue-400 bg-blue-400/10 border-blue-400/20";
        }
    };

    return (
        <div className="p-8">
            <header className="flex justify-between items-end mb-10">
                <div>
                    <h2 className="text-3xl font-bold text-white mb-2 flex items-center gap-3">
                        <ShieldCheck className="text-[#66fcf1]" />
                        Self-Healing Insights
                    </h2>
                    <p className="text-gray-500 text-sm">Autonomous patches and architectural improvements generated by the Heal Engine.</p>
                </div>
            </header>

            {/* Metrics */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
                <div className="glass-card">
                    <p className="text-xs font-bold text-[#45a29e] uppercase tracking-wider mb-2">Pending Approvals</p>
                    <h3 className="text-3xl font-bold text-white">
                        {data?.data?.filter(i => i.status === "pending").length || 0}
                    </h3>
                </div>
                <div className="glass-card">
                    <p className="text-xs font-bold text-green-400 uppercase tracking-wider mb-2">Total Healed</p>
                    <h3 className="text-3xl font-bold text-white">
                        {data?.data?.filter(i => i.status === "applied").length || 0}
                    </h3>
                </div>
                <div className="glass-card">
                    <p className="text-xs font-bold text-[#66fcf1] uppercase tracking-wider mb-2">System Confidence</p>
                    <h3 className="text-3xl font-bold text-white">94%</h3>
                </div>
            </div>

            <div className="space-y-6">
                {isLoading ? (
                    <div className="text-center py-20 text-gray-500">Scanning for neural pattern fixes...</div>
                ) : data?.data?.map((improvement: any) => (
                    <div key={improvement.id} className="glass rounded-3xl p-6 border border-white/5 hover:border-white/10 transition-all">
                        <div className="flex justify-between items-start mb-6">
                            <div className="flex items-start gap-4">
                                <div className="p-3 bg-[#66fcf1]/10 rounded-2xl text-[#66fcf1]">
                                    <Code2 size={24} />
                                </div>
                                <div>
                                    <div className="flex items-center gap-3 mb-1">
                                        <h4 className="text-lg font-bold text-white">{improvement.target_file}</h4>
                                        <span className={`px-3 py-0.5 rounded-full text-[10px] font-bold border ${getStatusStyle(improvement.status)} uppercase tracking-widest`}>
                                            {improvement.status}
                                        </span>
                                    </div>
                                    <p className="text-sm text-gray-400">{improvement.instruction}</p>
                                </div>
                            </div>
                            
                            {improvement.status === "pending" && (
                                <div className="flex gap-2">
                                    <button 
                                        onClick={() => handleReject(improvement.id)}
                                        className="p-3 bg-red-500/10 text-red-400 rounded-xl hover:bg-red-500/20 transition-colors"
                                    >
                                        <X size={20} />
                                    </button>
                                    <button 
                                        onClick={() => handleApprove(improvement.id)}
                                        className="px-6 py-3 bg-[#66fcf1] text-[#0b0c10] rounded-xl font-bold flex items-center gap-2 hover:bg-[#45a29e] transition-colors"
                                    >
                                        <Check size={20} />
                                        Approve & Apply
                                    </button>
                                </div>
                            )}
                        </div>

                        {/* Patch Preview */}
                        <div className="bg-[#0b0c10]/50 rounded-2xl p-4 border border-white/5 font-mono text-[12px] overflow-hidden">
                            <div className="flex items-center gap-2 mb-3 text-gray-500 border-b border-white/5 pb-2">
                                <Terminal size={14} />
                                <span>Proposed Changes (Synthetic Patch)</span>
                            </div>
                            <pre className="text-gray-300 max-h-40 overflow-y-auto custom-scrollbar">
                                {improvement.proposed_patch}
                            </pre>
                        </div>

                        {/* Test Results */}
                        <div className="mt-4 flex items-center gap-6">
                            <div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wider">
                                <ShieldCheck size={14} className="text-green-400" />
                                <span className="text-gray-500">Syntax:</span>
                                <span className="text-green-400">PASSED</span>
                            </div>
                            <div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wider">
                                <Cpu size={14} className="text-[#66fcf1]" />
                                <span className="text-gray-500">Unit Tests:</span>
                                <span className="text-[#66fcf1]">COMPLETED (12/12)</span>
                            </div>
                            <div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wider ml-auto">
                                <Clock size={14} className="text-gray-600" />
                                <span className="text-gray-600">{new Date(improvement.created_at).toLocaleString()}</span>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
