"""add autonomy decision table

Revision ID: 971644420bb9
Revises: 3b517c6cb58a
Create Date: 2026-06-13 00:26:33.089194
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '971644420bb9'
down_revision: Union[str, None] = '3b517c6cb58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilgeapi_autonomy_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('active_autonomy_mode', sa.String(length=64), nullable=False),
    sa.Column('eligibility', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('requires_human_gate', sa.Boolean(), nullable=False),
    sa.Column('human_gate_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['bilgeapi_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bilgeapi_autonomy_decisions_correlation_id'), 'bilgeapi_autonomy_decisions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_bilgeapi_autonomy_decisions_created_at'), 'bilgeapi_autonomy_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_bilgeapi_autonomy_decisions_eligibility'), 'bilgeapi_autonomy_decisions', ['eligibility'], unique=False)
    op.create_index(op.f('ix_bilgeapi_autonomy_decisions_incident_id'), 'bilgeapi_autonomy_decisions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_bilgeapi_autonomy_decisions_risk_level'), 'bilgeapi_autonomy_decisions', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bilgeapi_autonomy_decisions_risk_level'), table_name='bilgeapi_autonomy_decisions')
    op.drop_index(op.f('ix_bilgeapi_autonomy_decisions_incident_id'), table_name='bilgeapi_autonomy_decisions')
    op.drop_index(op.f('ix_bilgeapi_autonomy_decisions_eligibility'), table_name='bilgeapi_autonomy_decisions')
    op.drop_index(op.f('ix_bilgeapi_autonomy_decisions_created_at'), table_name='bilgeapi_autonomy_decisions')
    op.drop_index(op.f('ix_bilgeapi_autonomy_decisions_correlation_id'), table_name='bilgeapi_autonomy_decisions')
    op.drop_table('bilgeapi_autonomy_decisions')
    # ### end Alembic commands ###
