"""add bilgeapi tables

Revision ID: c4acb1b4c9f7
Revises: 0019_fix_project_owner_fk
Create Date: 2026-06-04 20:16:27.906690
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = 'c4acb1b4c9f7'
down_revision: Union[str, None] = '0019_fix_project_owner_fk'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilgeapi_audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bilgeapi_audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bilgeapi_audit_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_audit_events_event_type'), ['event_type'], unique=False)

    op.create_table('bilgeapi_diagnostic_runs',
    sa.Column('diagnostic_id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('root_cause_hypothesis', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('diagnostic_id')
    )
    with op.batch_alter_table('bilgeapi_diagnostic_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bilgeapi_diagnostic_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_diagnostic_runs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_diagnostic_runs_status'), ['status'], unique=False)

    op.create_table('bilgeapi_incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_key', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bilgeapi_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bilgeapi_incidents_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_incidents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_incidents_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_incidents_project_key'), ['project_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_incidents_source_system'), ['source_system'], unique=False)

    op.create_table('bilgeapi_repair_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('diagnostic_id', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_reason', sa.Text(), nullable=False),
    sa.Column('dispatch_status', sa.String(length=32), nullable=False),
    sa.Column('external_reference', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bilgeapi_repair_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bilgeapi_repair_requests_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_repair_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_repair_requests_diagnostic_id'), ['diagnostic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_repair_requests_dispatch_status'), ['dispatch_status'], unique=False)

    op.create_table('bilgeapi_webhook_deliveries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('repair_request_id', sa.String(length=64), nullable=False),
    sa.Column('webhook_url', sa.String(length=256), nullable=False),
    sa.Column('status_code', sa.Float(), nullable=True),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('attempt_count', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bilgeapi_webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bilgeapi_webhook_deliveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bilgeapi_webhook_deliveries_repair_request_id'), ['repair_request_id'], unique=False)

    op.create_table('bilgeapi_findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('diagnostic_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['bilgeapi_diagnostic_runs.diagnostic_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bilgeapi_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bilgeapi_findings_diagnostic_id'), ['diagnostic_id'], unique=False)

    op.create_table('bilgeapi_recommendations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('diagnostic_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['bilgeapi_diagnostic_runs.diagnostic_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bilgeapi_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bilgeapi_recommendations_diagnostic_id'), ['diagnostic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bilgeapi_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bilgeapi_recommendations_diagnostic_id'))

    op.drop_table('bilgeapi_recommendations')
    with op.batch_alter_table('bilgeapi_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bilgeapi_findings_diagnostic_id'))

    op.drop_table('bilgeapi_findings')
    with op.batch_alter_table('bilgeapi_webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bilgeapi_webhook_deliveries_repair_request_id'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_webhook_deliveries_created_at'))

    op.drop_table('bilgeapi_webhook_deliveries')
    with op.batch_alter_table('bilgeapi_repair_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bilgeapi_repair_requests_dispatch_status'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_repair_requests_diagnostic_id'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_repair_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_repair_requests_approval_status'))

    op.drop_table('bilgeapi_repair_requests')
    with op.batch_alter_table('bilgeapi_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bilgeapi_incidents_source_system'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_incidents_project_key'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_incidents_environment'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_incidents_created_at'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_incidents_correlation_id'))

    op.drop_table('bilgeapi_incidents')
    with op.batch_alter_table('bilgeapi_diagnostic_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bilgeapi_diagnostic_runs_status'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_diagnostic_runs_incident_id'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_diagnostic_runs_created_at'))

    op.drop_table('bilgeapi_diagnostic_runs')
    with op.batch_alter_table('bilgeapi_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bilgeapi_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_bilgeapi_audit_events_correlation_id'))

    op.drop_table('bilgeapi_audit_events')
    # ### end Alembic commands ###
