"""add_phase_80_sovereign_goals_and_goal_id

Revision ID: 7cc9f44bc8d0
Revises: 33bbc921964e
Create Date: 2026-04-04 22:32:03.846350
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7cc9f44bc8d0'
down_revision: Union[str, None] = '33bbc921964e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sovereign_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('vision_statement', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('kpis', sa.JSON(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ceo_suggested_tasks', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('ceo_suggested_tasks', sa.Column('plan_hierarchy', sa.JSON(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('ceo_suggested_tasks', sa.Column('goal_id', sa.UUID(), nullable=True))
    op.add_column('ceo_suggested_tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('ceo_suggested_tasks', 'priority',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.create_foreign_key(None, 'ceo_suggested_tasks', 'projects', ['created_task_id'], ['id'])
    op.create_foreign_key(None, 'ceo_suggested_tasks', 'ceo_suggested_tasks', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'ceo_suggested_tasks', 'sovereign_goals', ['goal_id'], ['id'])
    op.drop_index(op.f('idx_llm_cost_logs_role'), table_name='llm_cost_logs')
    op.create_index(op.f('ix_llm_cost_logs_agent_role'), 'llm_cost_logs', ['agent_role'], unique=False)
    op.add_column('memories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.add_column('memories', sa.Column('cause_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_memories_cause_id'), 'memories', ['cause_id'], unique=False)
    op.create_index(op.f('ix_memories_parent_id'), 'memories', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'memories', 'memories', ['parent_id'], ['id'])
    op.add_column('projects', sa.Column('goal_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'sovereign_goals', ['goal_id'], ['id'], ondelete='SET NULL')
    op.alter_column('subtasks', 'inhibition_signals',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               existing_nullable=True)
    op.drop_constraint(op.f('subtasks_parent_id_fkey'), 'subtasks', type_='foreignkey')
    op.create_foreign_key(None, 'subtasks', 'subtasks', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.create_foreign_key(op.f('subtasks_parent_id_fkey'), 'subtasks', 'subtasks', ['parent_id'], ['id'], ondelete='SET NULL')
    op.alter_column('subtasks', 'inhibition_signals',
               existing_type=sa.JSON(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'goal_id')
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_index(op.f('ix_memories_parent_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_cause_id'), table_name='memories')
    op.drop_column('memories', 'cause_id')
    op.drop_column('memories', 'parent_id')
    op.drop_index(op.f('ix_llm_cost_logs_agent_role'), table_name='llm_cost_logs')
    op.create_index(op.f('idx_llm_cost_logs_role'), 'llm_cost_logs', ['agent_role'], unique=False)
    op.drop_constraint(None, 'ceo_suggested_tasks', type_='foreignkey')
    op.drop_constraint(None, 'ceo_suggested_tasks', type_='foreignkey')
    op.drop_constraint(None, 'ceo_suggested_tasks', type_='foreignkey')
    op.alter_column('ceo_suggested_tasks', 'priority',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_column('ceo_suggested_tasks', 'updated_at')
    op.drop_column('ceo_suggested_tasks', 'goal_id')
    op.drop_column('ceo_suggested_tasks', 'plan_hierarchy')
    op.drop_column('ceo_suggested_tasks', 'parent_id')
    op.drop_table('sovereign_goals')
    # ### end Alembic commands ###
