import os
import json
from typing import Dict, Any, Optional

from services.project_factory.artifacts import (
    load_policy_draft_pr_plan,
    load_policy_apply_preview,
    load_policy_governance_manifest,
    write_policy_pr_creation,
    write_policy_pr_status
)
from services.project_factory.policy_pr_safety import check_policy_pr_creation_safety
from services.project_factory.policy_git_workspace import PolicyGitWorkspace
from services.project_factory.policy_github_pr_adapter import PolicyGitHubPRAdapter
from services.project_factory.policy_pr_creation_logs import log_policy_pr_creation
from services.project_factory.models import PolicyPRCreationRequest

def execute_policy_pr_creation(
    proposal_id: str,
    request: PolicyPRCreationRequest,
    workspace_root: Optional[str] = None
) -> Dict[str, Any]:
    """
    Phase 18 main orchestration flow.
    """
    try:
        # 1. Load artifacts
        draft_pr_plan = load_policy_draft_pr_plan(proposal_id, workspace_root)
        if not draft_pr_plan or draft_pr_plan.get("proposal_id") != proposal_id:
            raise ValueError(f"Draft PR Plan for {proposal_id} not found or mismatch.")
            
        apply_preview = load_policy_apply_preview(proposal_id, workspace_root)
        if not apply_preview or apply_preview.get("proposal_id") != proposal_id:
            raise ValueError(f"Apply Preview for {proposal_id} not found or mismatch.")
            
        gov_manifest = load_policy_governance_manifest(proposal_id, workspace_root)
        if not gov_manifest or gov_manifest.get("proposal_id") != proposal_id:
            raise ValueError(f"Governance Manifest for {proposal_id} not found or mismatch.")
            
        # 2. Safety Re-check
        four_eyes = os.environ.get("POLICY_FOUR_EYES_REQUIRED", "false").lower() == "true"
        risks = check_policy_pr_creation_safety(
            request=request.model_dump(),
            draft_pr_plan=draft_pr_plan,
            apply_preview=apply_preview,
            governance_manifest=gov_manifest,
            four_eyes_required=four_eyes
        )
        
        if risks:
            _record_failure(proposal_id, request, "SAFETY_BLOCK", "; ".join(risks), workspace_root)
            raise ValueError(f"Safety re-check blocked PR creation: {risks}")
            
        # 3. Policy Git Workspace execution
        git_ws = PolicyGitWorkspace(workspace_root or os.getcwd())
        branch_name = draft_pr_plan["branch_name"]
        target_branch = draft_pr_plan["target_branch"]
        
        try:
            git_ws.checkout_new_branch(branch_name)
        except Exception as e:
            # Maybe branch exists, or git error. We abort safely.
            _record_failure(proposal_id, request, "GIT_CHECKOUT_FAILED", str(e), workspace_root)
            raise ValueError(f"Failed to create codex/ branch: {e}")
            
        files_to_apply = draft_pr_plan.get("files_to_apply", [])

        # Apply the policy file changes locally. This remains a sandboxed draft
        # PR mutation; direct production apply is still forbidden.
        modified_files = []
        for change in apply_preview.get("preview_changes", []):
            if change.get("change_type") not in ["APPEND", "MODIFY_LIST", "MODIFY", "ADD"]:
                continue
            target_file = change["target_file"]
            if target_file not in files_to_apply:
                raise ValueError(f"Preview change target is not in files_to_apply: {target_file}")
            full_path = os.path.join(workspace_root or os.getcwd(), target_file)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            with open(full_path, "a", encoding="utf-8") as f:
                f.write(f"\\n# Added via Policy Autopilot {proposal_id}\\n")
            if target_file not in modified_files:
                modified_files.append(target_file)
                
        # Stage files
        if files_to_apply:
            try:
                git_ws.add_files(files_to_apply)
                commit_sha = git_ws.commit(f"chore: policy autopilot proposal {proposal_id}")
            except Exception as e:
                _record_failure(proposal_id, request, "GIT_COMMIT_FAILED", str(e), workspace_root)
                raise ValueError(f"Failed to commit changes: {e}")
        else:
            commit_sha = "empty"
            
        # 4. GitHub PR Adapter execution
        adapter = PolicyGitHubPRAdapter(mode=request.mode)
        success, pr_url, reason = adapter.create_draft_pr(
            title=draft_pr_plan["draft_title"],
            head_branch=branch_name,
            base_branch=target_branch,
            body=f"Policy Draft PR for {proposal_id}. Generated by Refine Project Factory."
        )
        
        if not success:
            result = _record_blocked(proposal_id, request, branch_name, reason, workspace_root)
            return result
            
        # 5. Record Success
        result = {
            "proposal_id": proposal_id,
            "status": "POLICY_DRAFT_PR_CREATED",
            "branch_name": branch_name,
            "target_branch": target_branch,
            "commit_sha": commit_sha,
            "pr_url": pr_url,
            "is_draft": True,
            "merge_performed": False,
            "force_push_performed": False,
            "production_direct_write": False,
            "policy_files_modified": True,
            "modified_files": modified_files,
            "four_eyes_enforced": four_eyes
        }
        write_policy_pr_creation(proposal_id, result, workspace_root)
        write_policy_pr_status(proposal_id, {"status": "POLICY_PR_CREATED_WAITING_REVIEW", "proposal_id": proposal_id}, workspace_root)
        
        log_policy_pr_creation(
            action="CREATE_POLICY_DRAFT_PR_SUCCESS",
            proposal_id=proposal_id,
            operator_id=request.operator_id,
            rationale=request.rationale,
            status="POLICY_DRAFT_PR_CREATED",
            branch_name=branch_name,
            commit_sha=commit_sha,
            pr_url=pr_url,
            workspace_root=workspace_root
        )
        
        return result
        
    except ValueError as ve:
        raise
    except Exception as e:
        _record_failure(proposal_id, request, "UNEXPECTED_ERROR", str(e), workspace_root)
        raise ValueError(f"Unexpected error during PR creation: {e}")

def _record_blocked(proposal_id: str, request: PolicyPRCreationRequest, branch_name: str, reason: str, workspace_root: Optional[str]) -> Dict[str, Any]:
    result = {
        "proposal_id": proposal_id,
        "status": "POLICY_PR_CREATION_BLOCKED",
        "reason": reason,
        "branch_name": branch_name,
        "commit_sha": None,
        "pr_url": None,
        "is_draft": True,
        "merge_performed": False,
        "force_push_performed": False,
        "production_direct_write": False
    }
    write_policy_pr_creation(proposal_id, result, workspace_root)
    write_policy_pr_status(proposal_id, {"status": "POLICY_PR_CREATION_BLOCKED", "proposal_id": proposal_id}, workspace_root)
    
    log_policy_pr_creation(
        action="CREATE_POLICY_DRAFT_PR_BLOCKED",
        proposal_id=proposal_id,
        operator_id=request.operator_id,
        rationale=request.rationale,
        status="POLICY_PR_CREATION_BLOCKED",
        branch_name=branch_name,
        reason=reason,
        workspace_root=workspace_root
    )
    return result

def _record_failure(proposal_id: str, request: PolicyPRCreationRequest, reason_code: str, details: str, workspace_root: Optional[str]) -> None:
    result = {
        "proposal_id": proposal_id,
        "status": "POLICY_PR_CREATION_FAILED",
        "reason": reason_code,
        "details": details
    }
    write_policy_pr_creation(proposal_id, result, workspace_root)
    write_policy_pr_status(proposal_id, {"status": "POLICY_PR_CREATION_FAILED", "proposal_id": proposal_id}, workspace_root)
    
    log_policy_pr_creation(
        action="CREATE_POLICY_DRAFT_PR_FAILED",
        proposal_id=proposal_id,
        operator_id=request.operator_id,
        rationale=request.rationale,
        status="POLICY_PR_CREATION_FAILED",
        reason=f"{reason_code}: {details}",
        workspace_root=workspace_root
    )
