"""add_improvements_tables

Revision ID: d67ccf6e6920
Revises: 5d8a1c2b7e90
Create Date: 2026-06-06 08:05:15.329863
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd67ccf6e6920'
down_revision: Union[str, None] = '5d8a1c2b7e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bilgeapi_research_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bilgeapi_research_requests_created_at'), 'bilgeapi_research_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_bilgeapi_research_requests_incident_id'), 'bilgeapi_research_requests', ['incident_id'], unique=False)
    op.create_index(op.f('ix_bilgeapi_research_requests_status'), 'bilgeapi_research_requests', ['status'], unique=False)
    op.create_index(op.f('ix_bilgeapi_research_requests_tenant_id'), 'bilgeapi_research_requests', ['tenant_id'], unique=False)

    op.create_table('bilgeapi_research_evidences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('research_id', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('source_domain', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('raw_content_summary', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['bilgeapi_research_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bilgeapi_research_evidences_research_id'), 'bilgeapi_research_evidences', ['research_id'], unique=False)
    op.create_index(op.f('ix_bilgeapi_research_evidences_source_domain'), 'bilgeapi_research_evidences', ['source_domain'], unique=False)

    op.create_table('bilgeapi_improvement_proposals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('research_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('patch_code', sa.Text(), nullable=False),
    sa.Column('risk_analysis', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('gate_status', sa.String(length=32), nullable=False),
    sa.Column('gate_score', sa.Float(), nullable=True),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_for_human_apply', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['bilgeapi_research_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bilgeapi_improvement_proposals_approval_status'), 'bilgeapi_improvement_proposals', ['approval_status'], unique=False)
    op.create_index(op.f('ix_bilgeapi_improvement_proposals_created_at'), 'bilgeapi_improvement_proposals', ['created_at'], unique=False)
    op.create_index(op.f('ix_bilgeapi_improvement_proposals_gate_status'), 'bilgeapi_improvement_proposals', ['gate_status'], unique=False)
    op.create_index(op.f('ix_bilgeapi_improvement_proposals_ready_for_human_apply'), 'bilgeapi_improvement_proposals', ['ready_for_human_apply'], unique=False)
    op.create_index(op.f('ix_bilgeapi_improvement_proposals_research_id'), 'bilgeapi_improvement_proposals', ['research_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bilgeapi_improvement_proposals_research_id'), table_name='bilgeapi_improvement_proposals')
    op.drop_index(op.f('ix_bilgeapi_improvement_proposals_ready_for_human_apply'), table_name='bilgeapi_improvement_proposals')
    op.drop_index(op.f('ix_bilgeapi_improvement_proposals_gate_status'), table_name='bilgeapi_improvement_proposals')
    op.drop_index(op.f('ix_bilgeapi_improvement_proposals_created_at'), table_name='bilgeapi_improvement_proposals')
    op.drop_index(op.f('ix_bilgeapi_improvement_proposals_approval_status'), table_name='bilgeapi_improvement_proposals')
    op.drop_table('bilgeapi_improvement_proposals')

    op.drop_index(op.f('ix_bilgeapi_research_evidences_source_domain'), table_name='bilgeapi_research_evidences')
    op.drop_index(op.f('ix_bilgeapi_research_evidences_research_id'), table_name='bilgeapi_research_evidences')
    op.drop_table('bilgeapi_research_evidences')

    op.drop_index(op.f('ix_bilgeapi_research_requests_tenant_id'), table_name='bilgeapi_research_requests')
    op.drop_index(op.f('ix_bilgeapi_research_requests_status'), table_name='bilgeapi_research_requests')
    op.drop_index(op.f('ix_bilgeapi_research_requests_incident_id'), table_name='bilgeapi_research_requests')
    op.drop_index(op.f('ix_bilgeapi_research_requests_created_at'), table_name='bilgeapi_research_requests')
    op.drop_table('bilgeapi_research_requests')
    # ### end Alembic commands ###
